version: "3.9"
services:

  postgresql:
    image: postgres:14
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=hynky
      - POSTGRES_PASSWORD=sirecek007
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - db:/var/lib/postresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@info.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  web:
    build: .
    ports:
      - "8000:5000"
      - "443:5001"

    depends_on:
      - postgresql

volumes:
  db:


