//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrackyASusarny.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data_EFCoreServices_LocalizationService {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data_EFCoreServices_LocalizationService() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrackyASusarny.Resources.Data_EFCoreServices_LocalizationService", typeof(Data_EFCoreServices_LocalizationService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        internal static string Create_Reservation {
            get {
                return ResourceManager.GetString("Create Reservation", resourceCulture);
            }
        }
        
        internal static string Washing_Machine {
            get {
                return ResourceManager.GetString("Washing Machine", resourceCulture);
            }
        }
        
        internal static string Drying_Room {
            get {
                return ResourceManager.GetString("Drying Room", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        internal static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        internal static string Available_Entities {
            get {
                return ResourceManager.GetString("Available Entities", resourceCulture);
            }
        }
        
        internal static string Daily_borrows {
            get {
                return ResourceManager.GetString("Daily borrows", resourceCulture);
            }
        }
        
        internal static string Hourly_borrows {
            get {
                return ResourceManager.GetString("Hourly borrows", resourceCulture);
            }
        }
        
        internal static string Weekly_usage {
            get {
                return ResourceManager.GetString("Weekly usage", resourceCulture);
            }
        }
        
        internal static string Hourly_usage {
            get {
                return ResourceManager.GetString("Hourly usage", resourceCulture);
            }
        }
        
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Borrows {
            get {
                return ResourceManager.GetString("Borrows", resourceCulture);
            }
        }
        
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        internal static string Average_borrows {
            get {
                return ResourceManager.GetString("Average borrows", resourceCulture);
            }
        }
        
        internal static string Average_hourly_usage {
            get {
                return ResourceManager.GetString("Average hourly usage", resourceCulture);
            }
        }
        
        internal static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        internal static string Average_weekly_usage {
            get {
                return ResourceManager.GetString("Average weekly usage", resourceCulture);
            }
        }
        
        internal static string Day_of_Week {
            get {
                return ResourceManager.GetString("Day of Week", resourceCulture);
            }
        }
        
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string My_Account {
            get {
                return ResourceManager.GetString("My Account", resourceCulture);
            }
        }
        
        internal static string Admin_Panel {
            get {
                return ResourceManager.GetString("Admin Panel", resourceCulture);
            }
        }
        
        internal static string My_Balance {
            get {
                return ResourceManager.GetString("My Balance", resourceCulture);
            }
        }
        
        internal static string Add_money {
            get {
                return ResourceManager.GetString("Add money", resourceCulture);
            }
        }
        
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        internal static string My_Reservations {
            get {
                return ResourceManager.GetString("My Reservations", resourceCulture);
            }
        }
        
        internal static string Borrowable_Entity {
            get {
                return ResourceManager.GetString("Borrowable Entity", resourceCulture);
            }
        }
        
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        internal static string End_Time {
            get {
                return ResourceManager.GetString("End Time", resourceCulture);
            }
        }
        
        internal static string Old_Reservations {
            get {
                return ResourceManager.GetString("Old Reservations", resourceCulture);
            }
        }
        
        internal static string New_Reservations {
            get {
                return ResourceManager.GetString("New Reservations", resourceCulture);
            }
        }
        
        internal static string Manage_Borrows {
            get {
                return ResourceManager.GetString("Manage Borrows", resourceCulture);
            }
        }
        
        internal static string Manage_Reservations {
            get {
                return ResourceManager.GetString("Manage Reservations", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        internal static string Manually_Select {
            get {
                return ResourceManager.GetString("Manually Select", resourceCulture);
            }
        }
        
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        internal static string Date_Ranges {
            get {
                return ResourceManager.GetString("Date Ranges", resourceCulture);
            }
        }
        
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string Suggest_Reservation {
            get {
                return ResourceManager.GetString("Suggest Reservation", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string Manage_Models {
            get {
                return ResourceManager.GetString("Manage Models", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        internal static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        internal static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        internal static string Borrow_ID {
            get {
                return ResourceManager.GetString("Borrow ID", resourceCulture);
            }
        }
        
        internal static string Borrowable_Entity_ID {
            get {
                return ResourceManager.GetString("Borrowable Entity ID", resourceCulture);
            }
        }
        
        internal static string Reservation_ID {
            get {
                return ResourceManager.GetString("Reservation ID", resourceCulture);
            }
        }
        
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string User_ID {
            get {
                return ResourceManager.GetString("User ID", resourceCulture);
            }
        }
        
        internal static string File_Name {
            get {
                return ResourceManager.GetString("File Name", resourceCulture);
            }
        }
        
        internal static string Location_ID {
            get {
                return ResourceManager.GetString("Location ID", resourceCulture);
            }
        }
        
        internal static string xmin {
            get {
                return ResourceManager.GetString("xmin", resourceCulture);
            }
        }
        
        internal static string Borrow_Person {
            get {
                return ResourceManager.GetString("Borrow Person", resourceCulture);
            }
        }
        
        internal static string Borrow_Person_ID {
            get {
                return ResourceManager.GetString("Borrow Person ID", resourceCulture);
            }
        }
        
        internal static string Manual_ID {
            get {
                return ResourceManager.GetString("Manual ID", resourceCulture);
            }
        }
        
        internal static string Taken {
            get {
                return ResourceManager.GetString("Taken", resourceCulture);
            }
        }
        
        internal static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        internal static string Select_model_to_edit {
            get {
                return ResourceManager.GetString("Select model to edit", resourceCulture);
            }
        }
        
        internal static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        internal static string Unknown_Action {
            get {
                return ResourceManager.GetString("Unknown Action", resourceCulture);
            }
        }
        
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        internal static string Model_not_found {
            get {
                return ResourceManager.GetString("Model not found", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string User_Settings {
            get {
                return ResourceManager.GetString("User Settings", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Personal_Data {
            get {
                return ResourceManager.GetString("Personal Data", resourceCulture);
            }
        }
        
        internal static string Manage_Email {
            get {
                return ResourceManager.GetString("Manage Email", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string New_Email {
            get {
                return ResourceManager.GetString("New Email", resourceCulture);
            }
        }
        
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        internal static string Current_Password {
            get {
                return ResourceManager.GetString("Current Password", resourceCulture);
            }
        }
        
        internal static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Deleting_this_data_will_permanently_remove_your_account__and_this_cannot_be_recovered_ {
            get {
                return ResourceManager.GetString("Deleting this data will permanently remove your account, and this cannot be recov" +
                        "ered.", resourceCulture);
            }
        }
        
        internal static string Your_account_contains_personal_data_that_you_have_given_us__This_page_allows_you_to_download_or_delete_that_data_ {
            get {
                return ResourceManager.GetString("Your account contains personal data that you have given us. This page allows you " +
                        "to download or delete that data.", resourceCulture);
            }
        }
        
        internal static string Create_New_Account {
            get {
                return ResourceManager.GetString("Create New Account", resourceCulture);
            }
        }
        
        internal static string Change_Email {
            get {
                return ResourceManager.GetString("Change Email", resourceCulture);
            }
        }
        
        internal static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        internal static string Update_Password {
            get {
                return ResourceManager.GetString("Update Password", resourceCulture);
            }
        }
        
        internal static string Confirm_New_Password {
            get {
                return ResourceManager.GetString("Confirm New Password", resourceCulture);
            }
        }
        
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        internal static string Delete_Data_And_Close_My_Account {
            get {
                return ResourceManager.GetString("Delete Data And Close My Account", resourceCulture);
            }
        }
        
        internal static string Use_a_local_account_to_log_in {
            get {
                return ResourceManager.GetString("Use a local account to log in", resourceCulture);
            }
        }
        
        internal static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        internal static string Log_In {
            get {
                return ResourceManager.GetString("Log In", resourceCulture);
            }
        }
        
        internal static string Welcome_to_the_Washing_Machine_Drying_Room_Management_website_ {
            get {
                return ResourceManager.GetString("Welcome to the Washing Machine/Drying Room Management website!", resourceCulture);
            }
        }
        
        internal static string WM_DR_Manager {
            get {
                return ResourceManager.GetString("WM/DR Manager", resourceCulture);
            }
        }
        
        internal static string Do_you_want_to_make_this_entity {
            get {
                return ResourceManager.GetString("Do you want to make this entity", resourceCulture);
            }
        }
        
        internal static string The_item_has_been_marked_as {
            get {
                return ResourceManager.GetString("The item has been marked as", resourceCulture);
            }
        }
        
        internal static string No_item_selected {
            get {
                return ResourceManager.GetString("No item selected", resourceCulture);
            }
        }
        
        internal static string DefaultBe_is_null {
            get {
                return ResourceManager.GetString("DefaultBe is null", resourceCulture);
            }
        }
        
        internal static string No_borrow_selected {
            get {
                return ResourceManager.GetString("No borrow selected", resourceCulture);
            }
        }
        
        internal static string Borrow_ended {
            get {
                return ResourceManager.GetString("Borrow ended", resourceCulture);
            }
        }
        
        internal static string Added_money {
            get {
                return ResourceManager.GetString("Added money", resourceCulture);
            }
        }
        
        internal static string User_not_logged_in {
            get {
                return ResourceManager.GetString("User not logged in", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        internal static string Reservation_created {
            get {
                return ResourceManager.GetString("Reservation created", resourceCulture);
            }
        }
        
        internal static string Created_reservation {
            get {
                return ResourceManager.GetString("Created reservation", resourceCulture);
            }
        }
        
        internal static string The_duration_must_be_at_least {
            get {
                return ResourceManager.GetString("The duration must be at least", resourceCulture);
            }
        }
        
        internal static string hour_and_at_maximum {
            get {
                return ResourceManager.GetString("hour and at maximum", resourceCulture);
            }
        }
        
        internal static string Borrow_created {
            get {
                return ResourceManager.GetString("Borrow created", resourceCulture);
            }
        }
        
        internal static string Reservation_canceled {
            get {
                return ResourceManager.GetString("Reservation canceled", resourceCulture);
            }
        }
        
        internal static string Created_record {
            get {
                return ResourceManager.GetString("Created record", resourceCulture);
            }
        }
        
        internal static string Unable_to_create_record {
            get {
                return ResourceManager.GetString("Unable to create record", resourceCulture);
            }
        }
        
        internal static string Unable_to_update_record {
            get {
                return ResourceManager.GetString("Unable to update record", resourceCulture);
            }
        }
        
        internal static string Deleted_item {
            get {
                return ResourceManager.GetString("Deleted item", resourceCulture);
            }
        }
    }
}
