### YamlMime:ManagedReference
items:
- uid: App
  commentId: N:App
  id: App
  children:
  - App._Imports
  langs:
  - csharp
  - vb
  name: App
  nameWithType: App
  fullName: App
  type: Namespace
  assemblies:
  - App
references:
- uid: App._Imports
  commentId: T:App._Imports
  name: _Imports
  nameWithType: _Imports
  fullName: App._Imports
