# Your GitHub workflow file under .github/workflows/
name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:


jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Docfx Setup
      run: dotnet tool update -g docfx
    - name: DocFX Build
      working-directory: docfx_project
      run: docfx ./docfx.json
      continue-on-error: false

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
        
